---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build

- name: publish
  pull: never
  image: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_STAGE_TOKEN}
  settings:
    repo: spritsail/docker-publish
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 162bf9875ac73665164c1cef3203d7379bbe54cd40d17cb8d3cbcd5fed7dbfe1

...
