---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: spritsail/docker-publish

- name: publish
  pull: never
  image: spritsail/docker-publish
  settings:
    repo: spritsail/docker-publish
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: cca014d64d0fb1965a4d65d1802c104f3a40031d04007ce03135399c70f00bcc

...
