pipeline:
  build:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      # Pre-tag this image as to bootstrap itself (how meta..)
      - docker build --no-cache --pull -t spritsail/docker-publish:latest .

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    repo: spritsail/docker-publish
